---
- name: Install RedHat-like packages
  yum: name={{ item }} state=latest update_cache=yes
  with_items:
    - postfix
    - curl
    - ca-certificates
    - openssh-server
  when: ansible_os_family == "RedHat"

- name: Install Debian-like packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - postfix
    - curl
    - ca-certificates
    - openssh-server
  when: ansible_os_family == "Debian"
